In [1]:
from statistical_utilities import math_utilities as tools
import numpy as np

In [2]:
#Datos de longitud y período de
L = np.array([0.1,0.15,0.2,0.25,0.3,0.35,0.4])
T = np.array([0.65,0.79,0.9,1.01,1.1,1.2,1.27])

In [3]:
T_sqrd = np.array([0.65,0.79,0.9,1.01,1.1,1.2,1.27])**2
sigma_L = 0.01 # m
sigma_T = 0.05 # s
sigma_T_sqrd = 2*T*0.05

L,T_sqrd

(array([0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 ]),
 array([0.4225, 0.6241, 0.81  , 1.0201, 1.21  , 1.44  , 1.6129]))

In [4]:
tools.linear_w_regression(L,T_sqrd,sigma_L,sigma_T_sqrd)

m: 3.9930482390205055 uncertanty m: 0.3567056561510685
b: 0.021601823633292914 uncertanty b: 0.08097656396692683


array([3.99304824, 0.35670566, 0.02160182, 0.08097656])